version: '3.3'
services:
  db:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - mmt-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mmt

volumes:
  mmt-data: